# 请根据自身需求修改
app_title: xApp-test
app_summary: xxApp-test
app_description: xxxApp-test
app_version: 1.0.0
app_debug: true
app_log_serialize: false
app_log_outdir: ./logs
app_disable_docs: false
app_allow_credentials: true
app_allow_origins:
  - '*'
app_allow_methods:
  - '*'
app_allow_headers:
  - '*'
# #
db_drivername: sqlite
db_async_drivername: sqlite+aiosqlite
db_database: app_test.sqlite
db_username:
db_password:
db_host:
db_port:
db_charset:
redis_host: 127.0.0.1
redis_port: 6379
redis_db: 0
redis_password:
redis_max_connections:
# #
celery_broker_url: redis://:<password>@<host>:<port>/<db>
celery_backend_url: redis://:<password>@<host>:<port>/<db>
celery_timezone: Asia/Shanghai
celery_enable_utc: true
celery_task_serializer: json
celery_result_serializer: json
celery_accept_content: [ json ]
celery_task_ignore_result: false
celery_result_expire: 86400
celery_task_track_started: true
celery_worker_concurrency: 8
celery_worker_prefetch_multiplier: 2
celery_worker_max_tasks_per_child: 100
celery_broker_connection_retry_on_startup: true
celery_task_reject_on_worker_lost: true
